###
GET http://localhost:3000/mainsearch HTTP/1.1
content-type: application/json

{
    "input": "4"
}

### LOGIN 

POST http://localhost:3000/login
Content-Type: application/json

{
    "mail": "toto@tata.fr",
    "password": "azerty"
}

### Lougout

POST  http://localhost:3000/signout

