###
GET http://localhost:3000/mainsearch HTTP/1.1
content-type: application/json

{
    "input": "4"
}

### Route to find one professional
GET http://localhost:3000/searchOnePro
Content-Type: application/json

{
    "id": 2
}

### Route to find professionnals by location
GET http://localhost:3000/searchProByLocation
Content-Type: application/json

{
    "zipOrCity": "4"
}

### Route to create a new user (user registration)
POST http://localhost:3000/registration
Content-Type: application/json

{
    "first_name": "dsf",
    "last_name": "fdsf",
    "phone_number": "0679958989",
    "birth": "12/01/1985",
    "mail": "dzdddda@dz112da.fr",
    "password": "azerty",
    "role_id": 1
}

### Route to create a new user and shop (user registration)
POST http://localhost:3000/registration
Content-Type: application/json

{
    "first_name": "dsf",
    "last_name": "fdsf",
    "phone_number": "0679958989",
    "birth": "12/01/1985",
    "mail": "dzdda@dz112dkfjljmfmglads.fr",
    "password": "azerty",
    "role_id": 2,
    "shop": {
        "shop_name" : "BarbaBulle2",
        "opening_time" : "du lundi au dimanche 7/7! de 9h à 19h",
        "address_name" : "Place du Champ de Foire",
        "address_number" : 16,
        "city" : "Arnac-La-Poste",
        "postal_code" : "87160"
    }
}

### 
POST http://localhost:3000/registration
Content-Type: application/json

{
    "first_name": "dsf",
    "last_name": "fdsf",
    "phone_number": "0679958989",
    "birth": "12/01/1985",
    "mail": "toto@tata.fr",
    "password": "azerty",
    "role_id": 1
}




### Route to update a client profile
PUT http://localhost:3002/client/profile
Content-Type: application/json

{
    "id": 25,
    "first_name": "youpi",
}

### Route to update a professional profile
PUT http://localhost:3003/pro/profile
Content-Type: application/json

{
    "id": 19,
    "first_name": "youpi",
    "last_name": "super"
}

### LOGIN 
POST http://localhost:3000/login
Content-Type: application/json

{
    "mail": "toto@tata.fr",
    "password": "azerty"
}

### test
POST http://localhost:3001/pro/availableappointment
Content-Type: application/json

{
    "dateStart": "2020-12-01",
    "dateEnd": "2020-12-03",
    "startHour": "09:00",
    "endHour": "10:30",
    "shopID": 2
}







### Generate appointement

POST http://localhost:3000/pro/availableappointment
Content-Type: application/json

{
    "dateStart": "2020-12-01",
    "dateEnd": "2020-12-05",
    "starthour": "09:00",
    "endHour": "17:00",
    "shopID": 2,
    "slotStart": "2020-10-20 22:00:0+02",
    "slotEnd": "2020-10-20 22:29:59+02"
}